### ISSUE TITLE
Promotion check I

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#12212]
### 1. Mod version

5.0-alpha.03

### 2. Installed Components

Vox Populi with EUI

### 3. Describe the Issue

Highlander (Ski Infantry) is missing info in civilopedia.
<img width="670" height="323" alt="Image" src="https://github.com/user-attachments/assets/88fe8c25-5373-4a6b-bace-d7a5f8b27e93" />

Phalanx (Discipline) lost its adjacency bonus?
<img width="671" height="296" alt="Image" src="https://github.com/user-attachments/assets/484732df-b4eb-4750-9775-fa19000f61d1" />

Viking has no info about AOE damage.
There's an ability with value 10 added? What does it do?
<img width="669" height="283" alt="Image" src="https://github.com/user-attachments/assets/2f7fc730-2358-474f-88c8-463ceb1fbe37" />
<img width="252" height="121" alt="Image" src="https://github.com/user-attachments/assets/4c504d71-2254-435d-9bc6-7500be0e3a07" />

Woodsman definitely needs more descriptions.
<img width="688" height="365" alt="Image" src="https://github.com/user-attachments/assets/abe27bd4-0daa-49eb-b49d-f31a0d200a6e" />

**Comment by azum4roll** [comment]
But that's your mod's descriptions. Don't mind the Extended Information, that should be reworked.

My plans about a civilopedia rework:

1. Add icons for most primary types that don't have them (UnitCombatType and some TerrainType/FeatureType)
2. Remove yields from the left panels
3. Add panels for tables/columns referencing the non-yield types to the left
4. Make all "Extended Information" appear on debug mode only, with them directly printing out the database tables instead of attempting to parse the info (that are all hardcoded)

**Comment by adaneslavo** [comment]
Yes all of them are my descriptions that were a kind of reference to what has changed between the versions.

I tried to list all promotions that have missing info.

What about those that probably changed or have abilities missing (like Discipline or Viking). Can u confirm or check?

**Comment by adaneslavo** [comment]
I merged all promotion issues into one post.
I moved my questions up, leaving the stuff u want to correct later to the bottom.
I will fill that later, because I have few of them left to check.

**Comment by azum4roll** [comment]
Currently, none of the Extended Info is meant to be accurate. New columns/tables are rarely added to the code, and a lot of them need special handling since the default is %.

Promotion _HELP, however, is now supposed to be super accurate down to the wordings used. If you find any inaccuracy that's not already fixed in my PR, feel free to tell me.

**Comment by axatin** [comment]
> Currently, none of the Extended Info is meant to be accurate. New columns/tables are rarely added to the code, and a lot of them need special handling since the default is %.

If it's not accurate I'll hide it for now

**Comment by adaneslavo** [comment]
> > Currently, none of the Extended Info is meant to be accurate. New columns/tables are rarely added to the code, and a lot of them need special handling since the default is %.
> 
> If it's not accurate I'll hide it for now

I would prefer they stay as they are even though they are inaccurate. Very often small balance changes in vp are not included in the changelog and they help me track these changes during Promotion Overhaul updates.

**Comment by azum4roll** [comment]
To be fair, current VP promotion help is much more accurate than your mod's version.

**Comment by adaneslavo** [comment]
You mean the text or the values?
What texts u have in mind? 

That might be the true because u did many spellchecking during last months.

Though I dont like few things in it and still see the field for upgrade so I decided to continue it. And using this civilopedia thing I can do it online.

**Comment by azum4roll** [comment]
I mean wording differences like "+X% Combat Strength when attacking Cities" VS "+% Offensive RCS vs Cities" on Siege promotions.

If the column is generic CS, I won't use RCS.

There's also the extra explanation on things like Splash ("This Damage ignores damage reduction, but does not affect Units in Cities and Fortifications").
