### ISSUE TITLE
Loading a saved multiplayer game seems to run the same turn an extra time

### ISSUE THREAD

**Issue by Chuzzle** [LoneGazebo/Community-Patch-DLL#1383]
1. Loading a saved game to a specific turn gives the bonuses of the latest played turn an extra time. For example, if you reload to an earlier state after triggering the religion bonus yielding +300 on science, faith, culture, gold (...), the game will add those bonuses to the actual, previous, state. Similar issues seem to occur when healing units and producing buildings.

Game is running on a Windows 8 machine, directX 11. Restarting the game does not seem to solve the problem. I imagine clearing the cache might, but I'm not quite sure how to do that.

**Comment by HampusAstrom** [comment]
We (me and Chuzzle) can probably reproduce the problem if required. Just tell us how to extract the data. We are using the "CPProject Full EUI 1/23" multiplayer modpack as linked in http://forums.civfanatics.com/showthread.php?t=553187

**Comment by LoneGazebo** [comment]
Hmm...sounds like an issue with savestate processing, which - unfortunately - I don't have control over.

**Comment by ilteroi** [comment]
well, i've noticed that you get all the notifications for the turn a second time when an autosave is loaded. could this be related?

**Comment by LoneGazebo** [comment]
Could be, but I have no idea why.

**Comment by Chuzzle** [comment]
Hm, okay. Anyone else have a similar issue? Or have been able to play multiplayer without issues? Would it help saving during different phases of the turn or something?

The specific issue that made it super broken in this case was that the new era bonuses on way of transcendence triggering; are these somehow triggered differently from game-native things?

It's a really nice mod, and we'd love to be able to play it together. If not, we can at least keep single-playing it :)

**Comment by LoneGazebo** [comment]
All CP/CBP functionality behaves the same way as vanilla stuff, so it isn't a 'new' thing in that regard.

**Comment by MoiMagnus** [comment]
Same problem for me, but only since the new year (don't remember the exact version where it change, but that's approximatively the date).
In fact : 
Before : Player turns takes place before AI and Barbarian turn -> no problems
Now : Player turns takes place after AI and Barbarian turn -> when loading, one turn is repeated (or skipped, I've not look at the turn number, so I don't know if that the AI which play two times during the same turn, of if that's the player who skip his turns)

**Comment by MoiMagnus** [comment]
Is it fixed in the last beta ?

**Comment by MoiMagnus** [comment]
I've done more test with the last beta, so I have to add a lot of corrections to my previous posts : 

1) One turn is skipped, that's not the AI which play two times.
2) During the skipped turn, every automated things (moves, for example) act as if your turn takes place. => Everything behave as if you were forced to end your turn immediatly.

Another very interesting point : 
When playing in multiplayer with only one human, it seems that if I move part of my units before saving, no turn is skipped when loading. The turn seems to be skipped only when I save after having done "nothing", which is unfortunatly the case of AUTOSAVES.
I have to confirm that point by playing with at least one other human.

**Comment by LoneGazebo** [comment]
So don't load autosaves in MP? Is that the solution?

**Comment by MoiMagnus** [comment]
Don't load autosave AND don't save at the begining of a turn, because it will behave as an autosave.
I'm not completly sure of that, since the only setting I've test is : 
Multiplayer 1 human VS 1 AI

**Comment by J-d-H** [comment]
Are you sure that loading autosaves in MP worked before? As far as I know the latest BNW patch did only hide some symptoms, but didn't fix the cause nor all effects of it. It may be possible that this bug was fixed in the community mod though.

One approach that should work with both, normal- and auto-saves, would be to keep loading from running CvGame::doTurn and only activate the active players that where active from savegame without calling the method to activate them.
=> either save all flags needed (I know, that vanilla doesn't save everything in this regard) or activate the players without calling the normal method (we need to avoid resetting the unit move count).

**Comment by MoiMagnus** [comment]
Not sure that loading autosaves in MP worked correctly before, but during games done last year, I don't remember having the problem of AI playing two times because you skipped your turn. But when you're not at war, you can easily miss that fact.

**Comment by MoiMagnus** [comment]
I've done another sequence of tests, and I was false on multiple points
=> Sorry for misleading you

The problem seems to be linked to the "hybrid" and "simultaneous" game mode.
I've not fully test it, but it seems to work correctly in "sequencial".
The reason why it was working before the new year was that we were playing in sequencial.

I've not manage to reproduce my previous test with the last beta : in hybrid, even with one human, one turn is always skipped when loading. Remark : Sometimes, lauching a game with one human player (againt one AI, on a tiny map, hybrid mode) make the game crash when generating the map (with proba 75% on my tests)

Moreover, during my last game, there were a lot of desync due to random generator : for example, an ancient ruin gives 3 tiles -> End of the turn -> desync -> the player have one pop in capital instead of the 3 tiles.
