### ISSUE TITLE
Bug with IsLostOnMove

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#260]
I noted a few months ago how IsLostOnMove doesn't work correctly with promotions that apply to Ocean or Coast. The idea is that embarked units would receive a promotion assigned to Coast and Ocean via LocationUnitFreePromotion, and then it would be removed when they disembark onto land. However, setting IsLostOnMove to true results in the coast/ocean promotion to not appear at all; leaving it false, on the other hand, means embarked units retain the promotion as they disembark onto land. All other terrains seem to work, so it appears to be an issue with transitioning between water and land. It would be helpful to see this fixed in the next version, if possible.

**Comment by LoneGazebo** [comment]
I believe I fixed this when you noted it – try it again and let me know?
G

**Comment by JFDaly** [comment]
That's why I brought it up. I'm preparing the next update to my Exploration Continued, in which I was continuing with adapting my attrition system to the new promotion and terrain tables, and I discovered that the issue with ocean/coast was still there (and this was on the latest version of the CP).

It's been a while, so the issue I reported back then was probably somewhat different to the issue I'm having now. Regardless it doesn't seem to be working as intended, like any other terrain.

**Comment by LoneGazebo** [comment]
Odd. I'll work on it tonight. 
G

**Comment by LoneGazebo** [comment]
Latest version has  a fix for this - test and get back to me.

**Comment by JFDaly** [comment]
Unfortunately the issue is still there - IsLostOnMove set to true means that the promotion just doesn't appear. If it's too much trouble, I can just have the promotion apply only to naval units and I can handle embarked units in Lua.

**Comment by LoneGazebo** [comment]
I'll figure it out, no worries.
G

**Comment by LoneGazebo** [comment]
Fixed. Definitely works now. I was able to make a promotion that was ocean only, and a promotion that was coast only, and both appeared/disappeared as needed. Will be in next version (coming out tomorrow, likely).

**Comment by JFDaly** [comment]
Confirmed. All fixed. Thanks :)

**Comment by LoneGazebo** [comment]
I posted it last night but forgot to put a new version post up. Did you just happen to look at the new version? I was very sleepy. Glad it works!
