### ISSUE TITLE
GameEvents.GreatWorkCreated()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#783]
It might've fallen under the radar, but did you see if you could fix GameEvents.GreatWorkCreated() so that it passed the Great Work ID as one of its parameters? The playerID parameter now works (as discussed), but the Great Work ID still returns nil. Would appreciate it if you could take a look.

**Comment by LoneGazebo** [comment]
Interesting, I thought I fixed this. I'll tweak some things and, in the next version, let me know if it works or not.
G

**Comment by LoneGazebo** [comment]
Okay, I tweaked this again – see if it works now. Should return either an INT, or the name of the GW.

**Comment by JFDaly** [comment]
With the latest version (the hotfix on the 20th), it seems to return a completely random integer where it should return the unit ID and returns nil for the great work ID (returns the playerID still, though).

**Comment by LoneGazebo** [comment]
Oh, I see what's wrong. In your initial post you said you wanted unit and gw, then you said you wanted player and gw. I didn't realize you want all three. Right now it gives you the player and the gw, but not the unit. I'll make it do all three next time.

**Comment by JFDaly** [comment]
I did factor that the unitID might have been replaced with the playerID, or that there was some confusion, but the Great Work ID still doesn't correspond to the Great Work produced. For instance, the ID returned is 296, corresponding to the Egg of Leda Great Work, but the actual Great Work produced is the Remains of the Magi - ID 370. This happens also with vanilla Great Works (those two are relics given out by Great Prophets).

**Comment by LoneGazebo** [comment]
I think it actually corresponds to the TXT ID because of how firaxis set all that up. In any case, I'll make it player, unit, GW ID in the next version and we'll go from there.

G

**Comment by LoneGazebo** [comment]
Here's the new code: GAMEEVENTINVOKE_HOOK(GAMEEVENT_GreatWorkCreated, getOwner(), GetID(), iGWindex);

**Comment by JFDaly** [comment]
Excellent, thank you.

**Comment by JFDaly** [comment]
Still nope. The GreatWorkID corresponds to how many times a unit has been expended for a Great Work (so, expontentially increases by 1 each time). Maybe it's just not possible?

**Comment by LoneGazebo** [comment]
That's really odd. And you used the same sequence as above? I'll keep exploring it, but the function is set to return the GW value. Hmm....

**Comment by JFDaly** [comment]
Yup, using it as above. But I thought of a workaround to retrieve the Great Work ID, by pulling the unit's unique name with Unit:GetNameNoDesc() and iterating over the Unique_UnitNames table, then pulling the Great Work Type from that and iterating over the Great Works table. It's a bit long-winded, but it works - so you could just leave as is; the Great Work event is still very useful by itself.

**Comment by LoneGazebo** [comment]
I think I've fixed it. The GW index was iterative the the great works created in the game, not the works themselves. I've now got it throwing the GW type (as an integer) out, so we'll see if this does the trick.
G

**Comment by JFDaly** [comment]
It works! Hooray :D
