### ISSUE TITLE
Golden Age Doesn't Calculate Properly

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#830]
![image](https://cloud.githubusercontent.com/assets/13937047/11426830/7ff74726-9413-11e5-86dd-c7361a91de99.png)

When you add any building that yields golden age points without any happiness, this number doesn't change at all. But when you add a building that provides happiness(so basically adding golden age points), the number will change.

It is only a graphical bug because you can still reach a golden age with the golden age point yields, but you are unable to determine the correct amount of turns in order to reach a golden age.

**Comment by LoneGazebo** [comment]
This is just in EUI, yes?

**Comment by TechpriestEnginseer** [comment]
Most likely yes because I've seen it in the EUI.

**Comment by oalzubbi** [comment]
I remember reading somewhere that even though GAP are supposed to accrue while you were in a golden age, they actually weren't. I've noticed this as well, but wasn't sure if I was just miscalculating. Whats the status on this?

**Comment by TechpriestEnginseer** [comment]
Well, based on my testing you can achieve a golden age with the acquired GAP, but in this issue, the EUI counter isn't calculating what turns you will achieve the golden age because it is only calculating the happiness rather than along with the GAP.

**Comment by Radost** [comment]
Only the GAP from happiness doesn't add during GAs, all other sources work just fine.
In my old autocracy germany game, I remember seeing -100 turns once GA has wore off.

**Comment by LoneGazebo** [comment]
I've fixed this in the 11-20 version (the EUI countdown in the top panel).

GAP points don't accrue during Golden Ages, or rather, I should say, they really shouldn't, as there's a potential for a nasty overflow bug. If they are, let me know with whom and where (i.e. Radost's mention of Germany), as that's a bug.

**Comment by Radost** [comment]
How nasty is that? The game I mentioned had 60+ cities with old UA and Might maxed, along with Angkor Wat at my disposal. So basically 10+ tile expands per turn.
Also, be careful with that "bug fix", as it will heavily undermine the GAP yield.

**Comment by LoneGazebo** [comment]
I'll take a look, but like I said, this isn't a 'nerf' or an attempt to 'undermine' the yield, but rather an oversight in how the overflow model is managed.

**Comment by Edaka** [comment]
I reckon you might not have worked on this yet, but I'll chime in to say the counter is still not displaying remaining turns until a GA right for GAP sources other than happiness: 
![gap](https://cloud.githubusercontent.com/assets/12978597/11520969/af2a693c-98b0-11e5-9e30-81f6624c5375.jpg)
This is with the 11/30 version.

**Comment by TechpriestEnginseer** [comment]
Pretty much. :+1:

**Comment by LoneGazebo** [comment]
I updated it - talking about EUI, right? I'll check the math - may need to 100x it.
G

**Comment by LoneGazebo** [comment]
I think I've fixed it for next version.
G
