### ISSUE TITLE
12/18 Harbor connection creating railroad connection too

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#958]
<img width="680" alt="sin titulo" src="https://cloud.githubusercontent.com/assets/13163824/11915617/cd0452e0-a6ae-11e5-9f6f-5763f9d7e77f.png">

**Comment by TechpriestEnginseer** [comment]
Pretty sure this is intentional after you researched the technology for the railroad ever since vanilla.

**Comment by Iamblichos** [comment]
At turn 38 with 11 science?

**Comment by Mitchsp** [comment]
Techpriest
Yes, but it's still very early game, I haven't researched the wheel even.

Iamblichos
And two turns after +6 when founding the Pantheon "God of Commerce" :) This is the 3rd city, in the early game I found in the early turns a friendly maritime city state and a +pop ruin allowing a great start.

**Comment by ilteroi** [comment]
small copy/paste error. should be fixed.

**Comment by Mitchsp** [comment]
Ilteroi, can the fix be done easily changing some file? If it's the case and you can tell me how I would like try to do and continue the game, thanks.
If isn't the case I'll wait to the fix with next version, no problem.

**Comment by ilteroi** [comment]
easy, new dll is up at https://dl.dropboxusercontent.com/u/16988401/civ/CvGameCore_Expansion2.zip

didn't test it yet though. just fixed the obvious typo and rebuilt

**Comment by Mitchsp** [comment]
Thanks ilteroi, very kind! I'll try later and report if  there's any problem.

**Comment by Mitchsp** [comment]
Bad news, the problem is still there. I've cleared the cache and tried both the saved game and a new one.

**Comment by ilteroi** [comment]
ah, it seems it's not related to harbors actually. railroad bonus for everyone right now ...

**Comment by Mitchsp** [comment]
Ok, so I assume that the fix will take longer, no prob.

**Comment by ilteroi** [comment]
will post a new build in the main forum

**Comment by Mitchsp** [comment]
Tried the new build, and unfortunately the bug still persist

**Comment by Edaka** [comment]
ilteroi, I hope you won't mind if I reopen for you. Keep rocking! (:

**Comment by ilteroi** [comment]
grr. try again please. same place

**Comment by Mitchsp** [comment]
Which version try again? the posted here or the forum one?

**Comment by ilteroi** [comment]
nice. closing this for good then. hopefully
